Refactor paging from recursive mapping to linear mapping
oscourse-tsinghua/rcore_plus pull request #50
Opened 2019-05-11 05:20 UTC by wangrunji0408

## Motivation
The current page table use recursive mapping to access itself and do not have a linear mapping to all physical memory.

This mechanism follows BlogOS. It worked well at the beginning.

But we found several limitations as our OS grows:
1. It's a really complicated concept that hard to understand for beginners. 
2. For some architectures, recursive mapping can not be implemented normally. For example, RISC-V and MIPS.
3. It's not easy to access page table and data of other processes. So forking process and coping the memory can not be implemented both simply and efficiently.
4. All access to an inactive page table needs to modify the active one, which causes unnecessary data race on multi-thread and multi-core.
5. It discourages us to access physical memory directly, which is unfriendly to driver and DMA.

Almost everyone agrees that linear mapping is a better choice.

## Changes
1. Merge `InactivePageTable` and `PageTable` trait.
2. Add `phys_to_virt` function.
3. Remove all DMA mappings in drivers.
4. ...

## Progress

|Arch|Status|Note|
|----|----|----|
| x86_64 |✅|  |
| RISC-V |❌| @jiegec  is WIP |
| AArch64 |❌| aarch64 crate support is needed |
| MIPS |✅| |

2019-05-11 06:39 UTC, miskcoo reviewed
It looks good for MIPS.

2019-05-11 11:30 UTC, Harry-Chen requested changes
MIPS part looks good to me, but RISC-V part seems not done yet

2019-05-11 11:30 UTC, Harry-Chen commented on kernel/src/drivers/block/virtio_blk.rs
> +<<<<<<< HEAD
Why is here merge conflicts?

2019-05-11 17:43 UTC, jiegec commented
Still one remain problem: #[repr(align(64)]] does not work with rv64.

2019-05-12 13:27 UTC, jiegec commented
RV32+64 is ready now.

2019-05-12 13:32 UTC, Harry-Chen approved these changes

2019-05-12 13:33 UTC, jiegec approved these changes

2019-05-12 14:30 UTC, Harry-Chen commented
I believe it is now feasible to merge these commits

2019-05-12 14:30 UTC, merged

2019-05-12 14:44 UTC, wangrunji0408 commented
Then aarch64 is broken. 😂
@equation314 Could you help fix linear mapping on aarch64?

2019-05-13 06:19 UTC, equation314 commented
OK, I will try to work in it this week...